
kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src

steps:
- name: backend
  image: library/golang:1.7
  commands:
  - go get
  - go test

- name: frontend
  image: node:latest
  commands:
  - npm install
  - npm run tests
