working_dir: &working_dir ~/app

version: 2.1 
 
orbs: 
   
  python: circleci/python@1.2 
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 5
    docker: 
      - image: cimg/python:3.8 
     
    steps:
      - checkout
      - run: git clone  https://gitlab.com/renifer12/cocol && cd cocol &&  python run.py